### ISSUE TITLE
Explanation to why one might need this and use cases

### ISSUE THREAD

**Issue by deresegetachew** [barbuza/react-saga#1]
Hi @barbuza i was wondering what problem this solves and what the use cases are; if you have blogged about it or have a detailed sample it would be very nice. It sounds interesting but i am confused to what it does.

**Comment by barbuza** [comment]
@derese that's an attempt to make data / logic dependencies declarative in the same way as UI. following code manages 3 sagas (`AuthenticatedApi`, `AnotherAuthenticatedSaga`, `GuestApi`) based on authentication state and current user id. `react-saga` forks / cancels sagas based on their presence in render tree and passed props. in this case `AnotherAuthenticatedSaga` is running when user is authenticated, `AuthenticatedApi` is running when authenticated as well, but restarts on `userId` changes.

```es6
import React from 'react';
import { put } from 'redux-saga';
import { reactSaga, Group } from 'react-saga';

function *AuthenticatedApi({ userId }) {
  yield put({ type: 'USER_ID_CHANGED', userId });
  while (true) {
    // handle authenticated api calls
  }
}

function *AnotherAuthenticatedSaga() {
  // whatever
}

function *GuestApi() {
  while (true) {
    // handle gust api calls
  }
}

function Api({ state: { authenticated, userId } }) {
  if (authenticated) {
    return (
      <Group>
        <AuthenticatedApi userId={userId}/>
        <AnotherAuthenticatedSaga/>
      </Group>
    );
  }
  return <GuestApi/>;
}

export default reactSaga(<Api/>);
```
